### ISSUE TITLE
Refactor Game State Logic

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#14]
# Issue Context

Currently the game page tracks whether a game is going on with the following data types in the _Quarto.elm_ file.
```
type Gamestatus
    = ActiveGame Activeplayer SelectedPiece
    | GameOver EndStatus


type EndStatus
    = GameWon Player
    | Draw
```

Notably, `EndStatus` is a parameter of one branch of the `Gamestatus` data type. However, this abstraction feels like it's unnecessary and causes tedious branching logic like
```
viewGamestatus gamestatus =
    case gamestatus of
        GameOver endstatus ->
            case endstatus of
                GameWon player ->
                    ...
                Draw ->
                    ...
```
Having to do this every time we need to check the game state is annoying.

# Suggested Solution

The proposal is to merge the two data types into one single union type with three branches
```
type Gamestatus
    = ActiveGame Activeplayer SelectedPiece
    | GameWon Player
    | Draw
```
Then, perform the necessary refactors to the update logic and the view to match the change to the model. That should hopefully simplify some of the game logic and reduce the cases of nested case statements.

# Alternatives Considered
N/A

# Additional Resources
N/A

**Comment by dominicduffin1** [comment]
I'm interested to have a go at this :)

**Comment by tkshill** [comment]
All yours!
