### ISSUE TITLE
Better Landing Page

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#15]
# Issue Context
The current Home/Landing Page has nothing on it. We'd like to have a better landing for users when they visit the application

# Suggested Solution
Solution should use the elm-UI library to generate the resulting html/css.
The landing page should have the following features:
- The word "Quarto" in large text centered on the page 
- Smaller heading text titled "What is Quarto and how do I play?"
- Include the following text taken from [this](https://en.wikipedia.org/wiki/Quarto_(board_game)) wikipedia article. Quoted text should be italicized or some other feature identifying it as a quote, with a reference afterwards to the wikipedia article (see below).
```
Quarto is a board game for two players invented by Swiss mathematician Blaise Müller. It is published and copyrighted by Gigamic.

The game is played on a 4×4 board. There are 16 unique pieces to play with, each of which is either:

    tall or short;
    red or blue (or a different pair of colors, e.g. light- or dark-stained wood);
    square or circular; and
    hollow-top or solid-top.

Players take turns choosing a piece which the other player must then place on the board. A player wins by placing a piece on the board which forms a horizontal, vertical, or diagonal row of four pieces, all of which have a common attribute (all short, all circular, etc.). A variant rule included in many editions gives a second way to win by placing four matching pieces in a 2×2 square.

Quarto is distinctive in that there is only one set of common pieces, rather than a set for one player and a different set for the other. It is therefore an impartial game. 

``` 
_- [Quarto (Board Game) Wikipedia]()_

# Alternatives Considered

## Bonus

For an extra challenge, add a footer to the `Shared.elm` file that contains a link to this github repository.

# Additional Resources
[Elm-UI library](https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/)

**Comment by paulmhan** [comment]
Hi I would love to help you out on this, can you assign it to me?

**Comment by tkshill** [comment]
Hi @paulmhan! Thank you for your interest. Unfortunately, the main issue has been assigned to someone already. But if you're still interested, maybe you can try to tackle the bonus? I can break it out into a separate issue after.

You would have to use the same setup as the main issue (elm-ui, etc) and the goal would be to make a footer that lives at the bottom of the page
- it should be the same colour as the header/nav bar (blue at the moment)
- It should use the colours from the Styles.elm module
- It should have a centered or right aligned link to the github repo
- you may or may not use the little github favicon image, totes up to you.

**Comment by paulmhan** [comment]
Sure, I can do that!
