### ISSUE TITLE
Update Page titles

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#16]
# Issue Context
The Page titles that appear in the tab bar are strange and don't follow the typical patterns of a normal web application.

# Suggested Solution
In each of the three page files `Top.elm`, `Quarto.elm`, and `NotFound.elm`, locate the top level view function
```
view : Url Params -> Document Msg
view { params } =
    { title = "Homepage"
      ....
```
Change the title parameters of each to the following
- For `Top.elm`, change the title from "Homepage" to "Quarto - Home"
- In `Quarto.elm`, change the title from "Game" to "Quarto - Play" 
- In `NotFound.elm`, change the title from "404" to "404 - Page not found" 

# Alternatives Considered
N/A

# Additional Resources
N/A

**Comment by arpanchhetri** [comment]
Can I pitch in?
