### ISSUE TITLE
Convert to Computer Player model

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#19]
# Issue Context
Currently, the app allows manual piece placement for both `Player1` and `Player2` which would mean two people could play by taking turns manipulating the same physical interface (keyboard, mouse, touchscreen). This is fine for a demo, but not a real application. We're not ready to introduce a backend yet, so we'll need to convert to a Player vs Computer model. This means that the app logic will have to take a different set of actions if it's a human player vs a computer player

# Suggested Solution
- Change the model (and subequent) Msg  type, update, and view functions to recognize a computer player or human player
- The computer player should pluck the first piece possible from the list of remaining pieces, and play it in the first board cell position available. 

# Alternatives Considered
N/A

# Additional Resources

See [here](https://github.com/tkshill/Quarto/blob/main/README.md#run-and-install) in the read me for how to run and install the application.

See [here](https://github.com/tkshill/Quarto/blob/main/CONTRIBUTING.md#the-basics) in contributing for the basics on forking and cloning the repository.

**Comment by danieltott** [comment]
I accept this challenge 

![42848D58-D53F-4CD1-A99A-35D41530F12C](https://user-images.githubusercontent.com/360261/95524032-43afa780-099e-11eb-8d03-aa81b9889e8b.gif)

**Comment by tkshill** [comment]
I love this energy. I was going to update the issue, but everything you'll be modifying is in the `Quarto.elm` file. I'd say give that file a look over before we tackle it tomorrow.
