### ISSUE TITLE
Add title in Index page

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#2]
# Context

Right now the app's homepage simply says `Homepage`. It would be better if it had a proper title reflecting the nature of the application.

# Action

- You will have to fork and clone the repository.
- Navigate to the `public/` folder in the repo
- Add the title html tag to the `index.html` file and call the application "Elm Quarto" or "Quarto".
- Test that this successfully changed the application title
- Merge changes and push back to your forked repo on GitHub
- Submit PR with change to this repository

# Completion criteria

When viewing the application in the browser, the tab title should be the one you defined in the title tag in index.html

**Comment by TaniaMalhotra** [comment]
Will work on this!
Please assign it to me

**Comment by sparshs413** [comment]
Please, assign me this task!!

**Comment by tkshill** [comment]
Hi folks,

Thank you so much for being interested in this project! I just want you to give you a heads up on a couple of things that we maybe haven't made clear on the readme yet (still a work in progress):

1. The main intent is that the hacktoberfest issues be tackled specifically during the month of October. At the very least we're leaving them open till then so everyone has equal opportunity for access. Hopefully we can get some non hacktoberfest issues up soon, which can be worked on at any time.
2. We really really really want certain issues, such as this one, to be reserved for absolute beginners (people with very little GitHub experience/almost no oss contributions yet).

Both of you seem to have quite a few commits, so we're asking that you maybe hold off on this issue, and tackle some of the others that we'll be putting up in the next few days/weeks that are a bit more challenging.

Thank you for understanding and being interested, we just really want the newest devs to have good opportunities.
