### ISSUE TITLE
Adding a title image/favicon

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#3]
# Context of Issue
As a modern web application it would be nice to have a favicon image in the browser tab. We want to be thorough and make sure we hit as many file formats as possible since the intent is to have this app work on multiple platforms.

# Suggested Solution
 After doing some research, it seems like the best method would be creating a favicon.ico with a collection of related images. Our suggested path would be:
- Go to this [Favicon Generator](https://favicon.io/favicon-generator/). Although this site makes favicons, they don't produce quite as details results as we would like, so we're just going to use them to generate a good source png.
- The text used should be "EQ" (for Elm Quarto)
- The shape should be square or square with rounded corners
- Choose an appropriate font for a favicon. Adjust the size until the text no longer touches the edges of the background square (but is still as large enough to be clearly legible in a tab corner)
- For the background and text colours you can use any mix of the following colours (these are the colours used by the elmlang [logo](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Ff%2Ff3%2FElm_logo.svg%2F1200px-Elm_logo.svg.png&f=1&nofb=1)). Please use a colour combo with strong contrast
  - #60B5CC
  - #7FD13B
  - #F0AD00
  - #5A6378
- Download the resulting ico folder.
- Next, go to the actual site we will be using to create our favicon ico, [realfavicongenerator](https://realfavicongenerator.net)
- Select the "android-chrome-512x512.png" image from the set that you downloaded earlier
- Use the default options except for the following
  - For the Favicon for Android Chrome section, select the _apply a slight drop shadow_ option
  - For the MacOS Safari section, select the _Turn your picture into a monochrome icon_ option. You may also adjust the colour to one of the colours suggested above.
  - In the Favicon Generator Options section, check both additional file option
- Click _Generate your Favicons and Html code_ to download the favicons folder
- Follow the guide to add the appropriate files to the project folder and modify the index.html file
- Wherever it says to use project "root" folder, that _should_ mean the repositories _public_ folder
- If successful, when you run the dev server, your newly made favicon should appear in the browser

# Alternatives (if relevant)
Contemplated a html solution but that seems to be less flexible than the ico method and will be supported by less browsers and other applications.

Note that I am not an expert in this type of thing. If there is a more sensible way to go about this while creating the same end result, please let me know.

# Additional Resources

**Comment by cambardell** [comment]
I can take this one if you want @tkshill, I've never touched elm so I can figure out the project structure while I'm doing this.

**Comment by tkshill** [comment]
Go for it buddy, and let me know if you want me to give you a walkthrough of the codebase.
