### ISSUE TITLE
Create a manifest.json file

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#4]
# Issue Context
To successfully create a Progressive Web App (A web application capable of being placed on a mobile home screen), we will need to add a manifest.json file with the right config information.

# Suggested Solution
- Clone and Fork the repository if you have not already
- navigate to the folder that contains the `index.html` file and add a `manifest.webmanifest` file
- add the following information to the file in json format (check the additional resources for some examples to layout)
  - "name" : "Elm Quarto"
  - "short_name" : "Elm Quarto"
  - "background_color": "#ffffff"
  - "display": "standalone"
  - "theme_color": "#000000"
  - "theme_color": "#000000"
- **IF** issue #3 has been resolved, then the app should contain a favicons folder and the following image information can be included as well (make sure the file paths/names all add up)
```
"icons": [
    {
      "src": "public/favicon-io/android-chrome-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "public/favicon-io/android-chrome-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
```
- Add the following html elements to the head of the `index.html` file if they don't exist already
```
<link rel="manifest" href="./manifest.webmanifest">
<link rel="apple-touch-icon" sizes="180x180" href="./icons/apple-touch-icon.png"> 
<link rel="icon" type="image/png" sizes="32x32" href="./favicon-io/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="./favicon-io/favicon-16x16.png">
<link rel="shortcut icon" href="./favicon-io/favicon.ico">
```
- Ensure the app still works correctly in your web browser after making these changes
- If no obvious errors are seen, commit your changes locally, push to your remote repo, and then from create a pull request back to this repo.

# Alternatives Considered

# Additional Resources
You can check out examples of other Elm project's manifest files [here](https://github.com/rametta/zucchini/blob/master/frontend/manifest.webmanifest), [here](https://github.com/Crafting-Computer/cpu-emulator-pwa/blob/master/www/manifest.json), and [here](https://github.com/Crafting-Computer/cpu-emulator-pwa/blob/master/www/manifest.json).

**Comment by CristhianMotoche** [comment]
Hi! Can I give you a hand with this?

**Comment by CristhianMotoche** [comment]
Oh, I noticed there is already a manifest [here](https://github.com/CristhianMotoche/Quarto/blob/main/public/favicon_package_v0/site.webmanifest). I suppose it's only necessary to update some particular attributes.

**Comment by tkshill** [comment]
Hi Cristhian, 

You're right. Someone already created a manifest file while solving another issue about adding favicon support and I hadn't updated this issue to say that.  But I definitely still am looking for someone to help adjust the manifest file so it has the right configurations for becoming a PWA.

Truth be told, I've never made a Progressive Web App before so it's hard for me to advise exactly what changes need to be made.

**Comment by CristhianMotoche** [comment]
Hi @tkshill I haven't made a PWA either. Nevertheless, the Mozilla [documentation](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps) suggests that:
> technically speaking it should have the following features: Secure contexts (HTTPS), one or more Service Workers, and a manifest file.

I can submit a PR to include the properties that you suggest and the ones that are specified [here](https://developer.mozilla.org/en-US/docs/Web/Manifest#Creating_a_valid_manifest) to create a valid manifest.
