### ISSUE TITLE
Feature Request: Have gamepiece buttons disabled when it's not the player's turn

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#48]
# Issue Context

Here we can see that the user can click a button even when it's the computer's turn to play. This should... not be so.

![Screenshot 2020-11-07 at 11 24 34](https://user-images.githubusercontent.com/13292886/98445116-4a8c2000-20ec-11eb-92e5-37259d41557e.png)

# Suggested Solution
Behind the scenes, an active game exists in one of four turn states

```elm
type Player
    = Human
    | Computer

type alias Winner =
    Player

type Turn
    = ChoosingPiece
    | ChoosingCellToPlay ChosenPiece

type GameStatus
    = InPlay ActivePlayer Turn
    | Won Winner
    | Draw
```
Based on these types, the valid gamestatuses can be 
`Inplay Human ChoosingPiece`
`Inplay Computer ChoosingPiece`
`Inplay Human ChoosingCellToPlay ChosenPiece`
`Inplay Computer ChoosingCellToPlay ChosenPiece`
`Won Winner`
`Draw`

Note that of these 6 options, the **only** time a game piece should be selectable is the first one, when a person is choosing a piece.

The view logic in `Top.elm` will have to be modified so the buttons are disabled except when the game is that specific turn state.

# Alternatives Considered

# Additional Resources

---
See [here](https://github.com/tkshill/Quarto/blob/main/README.md#run-and-install) in the read me for how to run and install the application.

See [here](https://github.com/tkshill/Quarto/blob/main/CONTRIBUTING.md#the-basics) in contributing for the basics on forking and cloning the repository.

**Comment by dominicduffin1** [comment]
I'd like to take this on!

**Comment by tkshill** [comment]
All yours my friend
