### ISSUE TITLE
Make the Restart button less ugly

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#49]
# Issue Context

The restart button is ugly.

![Screenshot 2020-11-07 at 11 16 24](https://user-images.githubusercontent.com/13292886/98449338-20952680-2109-11eb-9baa-0bcdade0b840.png)

Look at it. Hideous.

# Suggested Solution
- More spacing between the button and the text above.
- Center the button
- More padding between the button borders and the button text.

# Alternatives Considered

# Additional Resources
---
See [here](https://github.com/tkshill/Quarto/blob/main/README.md#run-and-install) in the read me for how to run and install the application.

See [here](https://github.com/tkshill/Quarto/blob/main/CONTRIBUTING.md#the-basics) in contributing for the basics on forking and cloning the repository.

**Comment by dominicduffin1** [comment]
I'd like to work on this!

**Comment by tkshill** [comment]
All yours my friend. Let me know if need any assitance
