### ISSUE TITLE
Add a Test.elm file

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#5]
# Issue Context
While this repo will be structured more along the lines of Domain Driven Development than Test Driven Development, we still need tests. The tests folder already exists, and the repository already has the two major elm testing frameworks, but the test folder itself currently only has a README file. 

# Suggested Solution
- if you have not done so already, fork the repo and create a local copy on your machine
- create a separate branch from main for the next few steps
- create a file `Test.elm` in the `tests/` folder
- add at least one passing test to this test file. 
  - this test should be called "first test" (passed as the first argument to the `test` function)
  - this test should always pass
- if the test compiles, run the test by opening your terminal/command line
- navigate to the root folder of the repository
- run `npm test`
- if the test runner finds the test, runs it, and declares it passed, then you're good!
- merge your test branch with main
- submit a PR for this feature

# Alternatives Considered
You're free to create additional tests you think may be valuable, but if you're new to elm, we suggest starting with a single passing test

# Additional Resources
- [Overview and Quick Start](https://package.elm-lang.org/packages/elm-explorations/test/latest) of Elm Test
- [this](https://package.elm-lang.org/packages/elm-explorations/test/latest/Test#test) is the test function in the elm test module
- [this](https://package.elm-lang.org/packages/elm-explorations/test/latest/Expect#pass) is the elm test function that always passes

**Comment by mrsantons** [comment]
Pretty please pick meeeee!
