### ISSUE TITLE
Add a noscript tag in the index.html file with a link to this github repo

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#58]
# Issue Context
We'd link to include an [< noscript >](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript) tag in the [index](https://github.com/tkshill/Quarto/blob/main/public/index.html) file. This will appear if anyone attempts to access the site but has disabled javascript on their browser. 

# Suggested Solution
Since the site **will not work at all** without javascript enabled, we simply want the elements in the noscript tag to
- [ ] Have some text telling the user that the site does not work without javascript
- [ ] Put a href link to link to [this repo](https://github.com/tkshill/Quarto) since github works without javascript enabled.

At the end, you can test it works by disabling javascript on the page. The explanation text and link should show up.

# Alternatives Considered
I have no clue how to make this site without js.

# Additional Resources
N/A
---
See [here](https://github.com/tkshill/Quarto/blob/main/README.md#run-and-install) in the read me for how to run and install the application.

See [here](https://github.com/tkshill/Quarto/blob/main/CONTRIBUTING.md#the-basics) in contributing for the basics on forking and cloning the repository.

**Comment by gervanna** [comment]
I will work on this issue.
