### ISSUE TITLE
Integrating with Travis CI

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#6]
# Issue Context
[Travis CI](https://docs.travis-ci.com/user/for-beginners/) is a continuous integration tool that can be used to automate the testing of our application before it is deployed. This repo is currently connected to a basic travis-CI pipeline and hosted on Netlify. However, to start using travis-CI features, we will need to add a `.travis.yml` file to the repository.

# Suggested Solution
- [clone and fork the repo](https://github.com/tkshill/Quarto/blob/main/CONTRIBUTING.md)
- Add a file called `.travis.yml` to the root repository
- add the following yaml code
```
language: elm

elm:
  - "latest-0.19.1"

elm-format: "0.8.2"

install: ":"

script:
  - elm-format --validate
  - elm-test
```
- [Submit PR with changes](https://github.com/tkshill/Quarto/blob/main/CONTRIBUTING.md)

**Note:** This is the maintainers first time working with Travis CI so we're not absolutely certain this is what's necessary. After PR is submitted we have to test to see if this actually produces the desired effect.

Anyone who has experience with Travis-CI is greatly appreciated but if you don't, this might be a great opportunity to learn!

# Alternatives Considered
N/A

# Additional Resources
- [elm section](https://docs.travis-ci.com/user/languages/elm/) of Travis CI documentation
- [Source](https://github.com/rtfeldman/elm-css/blob/master/.travis.yml) of code we're attempting to integrate

**Comment by greyGroot** [comment]
Could you please assign this task to me? i would like to try.

**Comment by tkshill** [comment]
Abandoning this issue for now. Between netlify integration and GitHub actions Travis CI probably isn't needed on this project at this time. Leaving it open so we remember to revisit the idea at a future date.
