### ISSUE TITLE
Restart Button

### ISSUE THREAD

**Issue by LeoUCon** [tkshill/Quarto#66]
# Issue Context
```
Player frustrated on how to restart game
```

# Suggested Solution
```
A restart button will be much better than having the players refresh the entire web page
```

See [here](https://github.com/tkshill/Quarto/blob/main/README.md#run-and-install) in the read me for how to run and install the application.

See [here](https://github.com/tkshill/Quarto/blob/main/CONTRIBUTING.md#the-basics) in contributing for the basics on forking and cloning the repository.

**Comment by tkshill** [comment]
thanks for the issue @LeoUCon!

I'd like to expand the context on the issue as well. Specifically, what does a good solution look like? Like, where should we place the button on the page? Once we establish that, I think we're more comfortable with opening it up for someone to tackle.
